---
name: Parser tests

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  pull_request:
    branches: [master, dev]
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  build:
    name: Parser tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python setup.py install
          pip install deepdiff
          pip install pytest

          git clone https://github.com/crytic/solc-select.git
          cd solc-select
          git checkout 857d6fa883d9283454be1cb2d869a8f9962b27b8
          cd ..
          ./solc-select/scripts/install.sh
          export PATH=/home/runner/.solc-select:$PATH
          echo "export PATH=/home/runner/.solc-select:$PATH" >> ~/.bashrc
          solc use 0.7.3

      - name: Test with pytest
        run: |
          pytest tests/test_ast_parsing.py

